# Generated by Django 5.1.6 on 2025-02-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='evaluadores',
            field=models.ManyToManyField(related_name='postulaciones', through='convocatorias.PostulacionEvaluadores', to='convocatorias.evaluador'),
        ),
    ]
