# Generated by Django 5.1.6 on 2025-02-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='anio_produccion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='duracion',
            field=models.TimeField(help_text='Formato HH:MM', verbose_name='Duración (Min)'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='enlace_vimeo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace del corto en Vimeo'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='fecha_resolucion_cpn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='resolucion_cpn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
