# Generated by Django 5.1.6 on 2025-02-11 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_alter_postulacion_anio_produccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='anio_fdc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año del beneficio'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='anio_produccion',
            field=models.IntegerField(verbose_name='Año de producción'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='beneficiario_fdc',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='El corto ha sido beneficiario de la convocatoria del FDC para cortos'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='celular_productor',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Número inválido. Use el formato: +573001234567 o 3001234567', regex='^\\+?\\d{1,15}$')], verbose_name='Número de celular del productor'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='certificacion_fdc',
            field=models.FileField(blank=True, null=True, upload_to='certificaciones/', verbose_name='Certificado del beneficio FDC'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='correo',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='correo_productor',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='domicilio_productor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='formato_grabacion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='nom_director',
            field=models.CharField(max_length=255, verbose_name='Nombre del director'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='nombre_productor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='productor_emp_produc',
            field=models.CharField(max_length=255, verbose_name='Productor o empresa productora'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='si_plataforma',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Cuales plataformas?'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='sinopsis_corta',
            field=models.TextField(verbose_name='Storyline / Sinopsis Corta'),
        ),
    ]
