# Generated by Django 5.1.6 on 2025-02-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_postulacion_evaluadores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='evaluador',
            options={'verbose_name': 'Evaluador', 'verbose_name_plural': 'Evaluadores'},
        ),
        migrations.AlterModelOptions(
            name='postulacion',
            options={'verbose_name': 'Postulación', 'verbose_name_plural': 'Postulaciones'},
        ),
        migrations.AlterModelOptions(
            name='postulacionevaluadores',
            options={'verbose_name': 'Asignación Curador', 'verbose_name_plural': 'Asignaciones Curador'},
        ),
    ]
