# Generated by Django 5.1.6 on 2025-02-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_alter_evaluacion_options_alter_evaluador_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='comentario_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
