# Generated by Django 5.1.6 on 2025-02-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0004_postulacion_comentario_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='plataformas_exhibicion',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=10),
        ),
    ]
