# Generated by Django 5.1.6 on 2025-02-14 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0004_evaluador_postulacion_evaluadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario del evaluador'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='recomendacion',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('discusion', 'Discusión')], max_length=10, null=True, verbose_name='¿Recomienda el corto para exhibición?'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='postulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='convocatorias.postulacion'),
        ),
    ]
