# Generated by Django 5.1.6 on 2025-02-17 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0005_remove_evaluacion_calificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionEvaluadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.evaluador')),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.postulacion')),
            ],
        ),
    ]
