# Generated by Django 5.1.6 on 2025-02-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0005_alter_postulacion_plataformas_exhibicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='correo',
        ),
    ]
