# Generated by Django 5.1.6 on 2025-02-25 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0006_remove_postulacion_correo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluador',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='evaluador',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='evaluador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluador', to=settings.AUTH_USER_MODEL),
        ),
    ]
