# Generated by Django 5.1.6 on 2025-02-17 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0006_postulacionevaluadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='convocatorias.evaluador'),
        ),
    ]
