# Generated by Django 5.1.6 on 2025-02-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0007_alter_evaluacion_evaluador'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='genero_cortrometraje',
            field=models.CharField(choices=[('ficcion', 'Ficción'), ('documental', 'Documental'), ('animacion', 'Animación'), ('experimental', 'Experimental'), ('hibrido', 'Híbrido')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='otro_subgenero_cortrometraje',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='subgenero_cortrometraje',
            field=models.CharField(choices=[('drama', 'Drama'), ('comedia', 'Comedia'), ('ciencia_ficcion', 'Ciencia Ficción'), ('ensayo', 'Ensayo'), ('suspenso', 'Suspenso'), ('musical', 'Musical'), ('otro', 'Otro')], default='no', max_length=20),
        ),
    ]
