# Generated by Django 5.1.6 on 2025-03-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0009_postulacion_comentario_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaevaluacion',
            name='archivo_privado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='actas/'),
        ),
        migrations.AddField(
            model_name='actaevaluacion',
            name='archivo_publico_pdf',
            field=models.FileField(blank=True, null=True, upload_to='actas/'),
        ),
        migrations.AlterField(
            model_name='actaevaluacion',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('acta_aprobada', 'Acta aprobada, lista para firmar'), ('firmada_jefe_area', 'Firmada por jefe de área')], default='en_proceso', max_length=50),
        ),
    ]
