# Generated by Django 5.1.6 on 2025-03-24 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0010_actaevaluacion_archivo_privado_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprobacionActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='convocatorias.actaevaluacion')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.evaluador')),
            ],
            options={
                'verbose_name': 'Aprobación de Acta',
                'verbose_name_plural': 'Aprobaciones de Actas',
                'unique_together': {('acta', 'evaluador')},
            },
        ),
    ]
