# Generated by Django 5.1.6 on 2025-03-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0012_alter_aprobacionacta_evaluador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaevaluacion',
            name='estado',
            field=models.CharField(choices=[('en_evaluaciones', 'En Evaluaciones'), ('en_aprobacion_acta', 'En aprobación de acta'), ('acta_aprobada', 'Acta aprobada (lista para firmar)'), ('firmada_jefe_area', 'Firmada por jefe de área')], default='en_evaluaciones', max_length=50),
        ),
    ]
