# Generated by Django 5.1.6 on 2025-03-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0014_alter_aprobacionacta_evaluador_bancocortos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='duracion',
            field=models.DurationField(verbose_name='Duración (MM:SS)'),
        ),
    ]
