# Generated by Django 5.1.6 on 2025-03-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0015_alter_postulacion_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='duracion',
            field=models.DurationField(help_text='Formato MM:SS', verbose_name='Duración (MM:SS)'),
        ),
    ]
